chucknorris/roundhouse

product/roundhouse/databases/DefaultDatabase.cs, product/roundhouse/infrastructure/persistence/IRepository.cs, product/roundhouse/infrastructure/persistence/Repository.cs
When running RoundhousE against Azure SQL it's painstakingly slow because of the round trips that RH makes just to check whether specific script has been ran and what's its hash. When you have over hundred scripts this latency really adds up. I've added a simple cache for looking up existing entries in database. 
I've also updated the NHibernate queries to use QueryOver which gives more compile-time safety
=> [Enhancement] cache information about already ran scripts to speed up script status checks

product/roundhouse.databases.sqlserver/SqlServerDatabase.cs, product/roundhouse.tests/databases/SqlServerDatabaseSpecs.cs
Azure Database server has name in the following format:
{randomsymbols}.database.windows.net - that "database" string occurrence
confuses code that parses connection string, making RH think that it's
a database name.
Fixed code in SqlServerDatabase that parses connection string to
retrieve server and database name. Use standard .Net
SqlConnectionStringBuilder utility for parsing instead of making
that by hand.
Note, that this code is fixed only for SqlServerDatabase, probably the similar thing should be applied to other databases as well.
This closes #192
=> Fix #192 - handle Azure Database connection strings

product/roundhouse.tasks/Roundhouse.cs
This commit does two things:
- converts `Roundhouse.RecoveryMode` to an explicit implementation of `ConfigurationPropertyHolder.RecoveryMode`
- adds a property with the same name of type `System.String`
Both properties get and set the same private field.
Fixes #131
=> Fix invalid usage of MSBuild task parameters

product/roundhouse.tasks/Roundhouse.cs, product/roundhouse.tasks/roundhouse.tasks.csproj
This PR adds a reference to Microsoft.Build.Utilities.v4.0 for its `TaskLoggingHelper` class.
Code that previously threw `ArgumentOutOfRangeException` now instead log an MSBuild error.
MSBuild errors that were logged using the `TaskLoggingHelper` now cause the Roundhouse task to exit early and crash the build script (unless `ContinueOnError=true`).
=> Improve MSBuild error handling for 'RecoveryMode'

product/roundhouse.databases.oracle/OracleDatabase.cs, product/roundhouse.databases.sqlserver/SqlServerDatabase.cs, product/roundhouse.databases.sqlserver2000/SqlServerDatabase.cs, product/roundhouse.tests/sqlsplitters/StatementSplitterSpecs.cs, product/roundhouse/databases/DefaultDatabase.cs
I believe this fixes #202.
I also applied an equivalent change to handle leading splitters in the other databases, but not sure if that's appropriate?
/cc @ChrisMissal
=> Handle files with leading batch splitter

product/roundhouse.console/Program.cs, product/roundhouse.tasks/Roundhouse.cs, product/roundhouse/consoles/DefaultConfiguration.cs, product/roundhouse/infrastructure.app/ConfigurationPropertyHolder.cs, product/roundhouse/infrastructure.app/builders/VersionResolverBuilder.cs, product/roundhouse/resolvers/CommandLineVersionResolver.cs, product/roundhouse/roundhouse.csproj, product/roundhouse/runners/RoundhouseMigrationRunner.cs
- Add CommandLineVersionResolver.cs which extracts version directly from a
string.
- Update VersionResolverBuilder.cs to include the new resolver. Logic
now groups the file based resolvers together and skips them if the
command line resolver is valid.
- Added Version property to the configuration objects.
- Fix small typo / spelling error (already submitted in Pull Request #134
=> (GH-120) Pass version number in the command line

product/roundhouse/databases/DefaultDatabase.cs, product/roundhouse/migrators/DefaultDatabaseMigrator.cs
Log an exception details when logging a warning event to simplify troubleshooting.
----
We've experienced following error when running RoundhousE on Azure Database:
```
2015-11-12 19:39:00,991 [WARN ] - 0001.SomeScript.sql - I didn't find this script executed before.
2015-11-12 19:39:01,929 [ERROR] - RoundhousE encountered an error.
System.Exception: 0001.SomeScript.sql has changed since the last time it was run. By default this is not allowed - scripts that run once should never change. To change this behavior to a warning, please set warnOnOneTimeScriptChanges to true and run again. Stopping execution.
at roundhouse.migrators.DefaultDatabaseMigrator.run_sql(String sql_to_run, String script_name, Boolean run_this_script_once, Boolean run_this_script_every_time, Int64 version_id, …
```
=> Provide error details when logging a warning event

product/roundhouse/infrastructure/persistence/NHibernateSessionFactoryBuilder.cs
This is to prevent Timeout Expired exceptions when migration is running
on a slow/high latency server (the case for Azure Sql Server) or a
database with a lot of update scripts recorded in a `ScriptsRun` table.
The timeout of 5 minutes is currently hard-coded. Probably the better
way would be to add an additional configuration option. On the other
hand I'm not sure user should care about that additional config option.
Relates to #237
=> (GH-237) Increase timeout for NHibernate commands

nuget/roundhouse.lib/roundhouse.lib.nuspec, nuget/roundhouse.msbuild/roundhouse.msbuild.nuspec
The NuGet packages depend on an older version of log4net than the version that is actually used throughout the code. This causes installation problems in most NuGet clients.
The lastest version is 1.2.15, roundhouse depends on 1.2.11, but the NuGet packages are configured to require exactly 1.2.10 instead of 1.2.11 or newer.
This PR fixes the version restriction, and makes it less strict because it causes problems in projects that use a newer version of log4net.
=> Fix log4net dependency

product/roundhouse/databases/DefaultDatabase.cs
This is to simplify troubleshooting when getting mysterious exceptions
from Azure like "CreateDatabaseAsyncV3 operation failed. Operation
timed out." Having exception type and stacktrace would be helpful.
=> Log error details when failed to create database

build/nugetPrepare.step
The duplicate versions caused a error on build of the nuget packages.
=> Duplicate PreRelase Version in NuGet version fixed.

product/roundhouse.tests/resolvers/TextVersionResolverSpecs.cs, product/roundhouse.tests/roundhouse.tests.csproj, product/roundhouse/resolvers/TextVersionResolver.cs
Added Trim to TextVerisonResolver class where it reads the version to remove any leading or trailing whitespace that may been added to the file.
=> (GH-240) Trim version file contents

product/roundhouse.console/Program.cs, product/roundhouse/Migrate.cs, product/roundhouse/migrators/DatabaseMigrator.cs, product/roundhouse/migrators/DefaultDatabaseMigrator.cs, product/roundhouse/roundhouse.csproj, product/roundhouse/runners/RoundhouseMigrationRunner.cs, product/roundhouse/runners/RoundhouseUpdateCheckRunner.cs
In our automated deployment scenario for a web application on load balanced web servers, we need to know if there are any changes to the database before running roundhouse. When there are db changes, we need to take take the application offline before updating. When there are only changes to the web app code, we can pull each server out of load balancer, update, and push it back in without any downtime.
To support this scenario, I have implemented the --isuptodate switch. It will simply tell if there are any db changes or not, in a way that is easy to interpret in a script. When combined with the --silent switch, the output is simply "Database is up to date: True" or "Database is up to date: False".
=> Implemented --isuptodate switch

product/roundhouse/databases/AdoNetDatabase.cs
Stop the AdoNetDatabase from sharing the same transaction across both
Admin and Default connections.
When using the with transaction option, it causes failures when creating databases running alter database scripts.
=> Fix transaction sharing between Admin and Default

product/roundhouse.console/Program.cs, product/roundhouse.tasks/Roundhouse.cs, product/roundhouse/consoles/DefaultConfiguration.cs, product/roundhouse/infrastructure.app/ConfigurationPropertyHolder.cs, product/roundhouse/infrastructure/filesystem/WindowsFileSystemAccess.cs
Add option "fileencoding=" which allows the RH to be told explicitly
what file encoding it should use to read files. If no encoding is
specified it falls back to the existing auto-detection logic.
This is useful if your script files are encoded in UTF-8 without the
BOM.
=> Add explicit file encoding option

build.custom/compile.post.step, build.custom/ilmergeDLL.build, product/roundhouse.databases.sqlserver/SqlServerDatabase.cs, product/roundhouse.databases.sqlserver/TransientErrorDetectionStrategy.cs, product/roundhouse.databases.sqlserver/packages.config, product/roundhouse.databases.sqlserver/roundhouse.databases.sqlserver.csproj, product/roundhouse/databases/AdoNetDatabase.cs, product/roundhouse/databases/DefaultDatabase.cs, product/roundhouse/infrastructure/extensions/ObjectExtensions.cs, product/roundhouse/infrastructure/persistence/Repository.cs, product/roundhouse/packages.config, product/roundhouse/roundhouse.csproj
This is to start discussion on issue #236 and to find out solution.
Added transient exception handling for SqlServer database. This is to
have a better support for Azure SQL Database where transient faults
are expected and happen periodically.
Support for transient fault handling is added in a base DefaultDatabase
class, but the retry strategy implementation is specified in a
concrete database provider (mssql in this case).
Transient faults are handled in following places:
- Transient faults when opening a connection
- Transient faults when running an update script
- Transient faults when dealing with RoundhousE internal tables (via
NHibernate).
Microsoft TransientFaultHandling library was referenced for retry
building blocks. This might look like a dependency that could be
avoided (by …
=> (GH-234) Fault tolerance for transient exceptions

product/roundhouse.console/Program.cs, product/roundhouse.console/packages.config, product/roundhouse.console/roundhouse.console.csproj, product/roundhouse.tasks/Roundhouse.cs, product/roundhouse/consoles/DefaultConfiguration.cs, product/roundhouse/infrastructure.app/ConfigurationPropertyHolder.cs, product/roundhouse/infrastructure/commandline.options/Options.cs
This change introduces a new command line parameter called ConfigurationFile (or configfile or cf), which can point to a simple JSON file.
If the path to a configuration file is provided, it will read properties from the JSON file, and if they match the available configuration values (in ConfigurationPropertyHolder interface), will will copy those values in to the configuration.
If a value does not exist in the configuration file, it will use the default or provided command line value.
If a value exists in the configuration value that does not exist in the ConfigurationPropertyHolder interface, it will be ignored.  
If a value exists but cannot be converted to the correct type (via Convert.ChangeType), it will display an error message.
This JSON works:
``` json
{
DatabaseName: …
```
=> [Enhancement] Add support for ConfigurationFile parameter

product/roundhouse.console/Program.cs, product/roundhouse.tasks/Roundhouse.cs, product/roundhouse.tests/migrators/DefaultDatabaseMigratorSpecs.cs, product/roundhouse/Migrate.cs, product/roundhouse/consoles/DefaultConfiguration.cs, product/roundhouse/environments/DefaultEnvironment.cs, product/roundhouse/environments/DefaultEnvironmentSet.cs, product/roundhouse/environments/EnvironmentSet.cs, product/roundhouse/infrastructure.app/ApplicationConfiguraton.cs, product/roundhouse/infrastructure.app/ConfigurationPropertyHolder.cs, product/roundhouse/migrators/DatabaseMigrator.cs, product/roundhouse/migrators/DefaultDatabaseMigrator.cs, product/roundhouse/roundhouse.csproj, product/roundhouse/runners/RoundhouseMigrationRunner.cs
Allows you to set multiple environments (e.g. _--environments=NEWZEALAND,CUSTOMER_).
If we have the following files:
0000 - main.sql
0001 - new zealand feature.NEWZEALAND.env.sql
0002 - australia feature.AUSTRALIA.env.sql
0003 - customer feature for any country.CUSTOMER.env.sql
Then script 0000, 0001 and 0003 will run, but not the Australia file.
Scripts are checked to see if they contain any environment from the environment set given (matching the current behaviour), remaining compatible with current use cases (i.e. https://groups.google.com/d/topic/chucknorrisframework/x2CAAWLgJ9I/discussion) and nothing needs to change for people who don't want to use multiple environments.
Three environment flags have been added to match the current 3:
Current: env, environment, environmentname
Added: …
=> {WIP}(GH-235) Add support for multiple environments

product/roundhouse.console/Program.cs
TLS 1.2 connections are failing when a connection is initialised to a database sever running TLS 1.2 only - this init method adds support for these connections.
=> Add init for tls 1.x support

Settings/UppercuT.config
The Nuget.exe in lib was removed in a prior commit (while the one in .nuget was updated). Without the lib version we
can't actually build packages for publishing. Rather than restore the redundant copy of the exe, I updated the build config
to reference the one that we do have.
=> Change NuGet.exe reference in build config

product/roundhouse.tests/cryptography/CryptographicServiceSpecs.cs
Test was performing 1M iterations over a 10K byte field. This was taking
60-90s depending on the machine. I dropped this to 2K iterations.
=> Speed up test for MD5 implementation equivalence

appveyor.yml
We should keep the appveyor.yml in the git repo. I don't have access to the one used in the chuchnorris project, but I created my own, and exported that appveyor.yml, to run only the unit tests (not integration tests), and add the .nupkgs to the build artifacts.
=> Add appveyor.yml to git repo

build.ps1, product/roundhouse.console/Program.cs, product/roundhouse.databases.sqlserver/SqlServerDatabase.cs, product/roundhouse.tasks/Roundhouse.cs, product/roundhouse.tests.integration/infrastructure/persistence/NHibernateSessionFactorySpecs.cs, product/roundhouse.tests/infrastructure.app/tokens/TokenReplacerSpecs.cs, product/roundhouse.tests/runners/RoundhouseMigratorRunnerSpecs.cs, product/roundhouse/Migrate.cs, product/roundhouse/runners/RoundhouseMigrationRunner.cs
Didn't know what to do with the last ones, as they're obsolete APIs actually exposes via command-line parameters. Should we remove them from the command line options too? They've probably been deprecated for 4 years, but has the deprecation been communicated to end-users of `rh.exe`, or can we expect someone to rely on those? And if, should we care? Or just announce a breaking change?
=> Removed some warnings in the build

product/roundhouse.console/Program.cs, product/roundhouse.tasks/Roundhouse.cs, product/roundhouse.tests/migrators/DefaultDatabaseMigratorSpecs.cs, product/roundhouse.tests/runners/RoundhouseMigratorRunnerSpecs.cs, product/roundhouse/consoles/DefaultConfiguration.cs, product/roundhouse/environments/DefaultEnvironmentSet.cs, product/roundhouse/infrastructure.app/ApplicationConfiguraton.cs, product/roundhouse/infrastructure.app/ConfigurationPropertyHolder.cs
Includes and supersedes #296 
EnvironmentName is restored (and marked obsolete), but is now implemented in terms of EnvironmentNames and the splitting is done immediately.
=> Erikbra fix too eager delete

GitVersion.yml, appveyor.yml, build.ps1
Added GitVersion-config that is supposed to work when we work in a GitHubFlow style (i.e. no separate develop-branch, just PRs off master). Versions from tags, and uses semantic versioning for commits after a release. Uses `pre` as suffix for builds not from a tag.
`master` as of now should be `0.8.9-pre.X`
when we are ready for release, we just tag master with `0.8.9`, and the version number becomes `0.8.9` (no suffix).
=> Add GitVersion-config

appveyor.yml
Add a step to push to MyGet from the AppVeyor builds. Uses encryptet MyGet ApiKey (needs to be inserted, of course), using [https://ci.appveyor.com/tools/encrypt](https://ci.appveyor.com/tools/encrypt). It encrypts with a unique key per AppVeyor account. 
It would be really nice if AppVeyor supported merging of AppVeyor.yml and GUI, because then we could put the URI to the MyGet feed (which varies for e.g. erikbra and roundhouse) and the Api Key in the GUI instead of the checked-in file. But it does the job.
This only pushes "proper" builds (not builds of PRs). So we would push (of course with a -pre tag if #300 is merged too) whenever master is built on its own, but not on PR builds.
=> {WIP} Add push to MyGet from AppVeyor builds

product/roundhouse.console/roundhouse.console.csproj, product/roundhouse.console/roundhouse.nuspec, product/roundhouse.databases.access/roundhouse.databases.access.csproj, product/roundhouse.databases.mysql/roundhouse.databases.mysql.csproj, product/roundhouse.databases.postgresql/roundhouse.databases.postgresql.csproj, product/roundhouse.databases.sqlite/roundhouse.databases.sqlite.csproj, product/roundhouse.databases.sqlserver/roundhouse.databases.sqlserver.csproj, product/roundhouse.lib.merged/roundhouse.lib.merged.csproj, product/roundhouse.lib.merged/roundhouse.lib.nuspec, product/roundhouse/roundhouse.csproj, roundhouse.sln
Added another project, just for the merge of all the DLLs into one for
Nuget packaging. Made more of the original Nuget dependencies proper
dependencies of roundhouse.lib instead of merging some of them. I think
merging them might lead to problems if someone uses both roundhouse.lib
and one of the original dependency nuget packages.
=> Fixed Issue #306 - added roundhouse.lib.merged

appveyor.yml, product/roundhouse.console/rh.bat, product/roundhouse.console/roundhouse.console.csproj
It't easier to test the netcore version on Windows if distributed as a
.zip, and with at .bat file to execute.
=> Added rh.bat and .zip packaging

product/roundhouse.tasks/Roundhouse.cs, product/roundhouse.tests/infrastructure.app/DefaultConfigurationSpecs.cs, product/roundhouse/consoles/DefaultConfiguration.cs, product/roundhouse/infrastructure.app/ConfigurationPropertyHolder.cs, product/roundhouse/infrastructure.app/tokens/TokenReplacer.cs
This will move the creation of the token dictionary out of TokenReplacer and into the ConfigurationPropertyHolder implementation. Along the way, #328 will be fixed.
A few questions:
1. The **roundhouse** project has the C# language version set to 5 - I assume this is intentional but I'd just like to make sure. nameof() and collection initialization are unavailable in C# 5.
2. I've dropped the `DefaultEncoding` and `Logger` properties from the dictionary - are there others that aren't appropriate? They're all primitive types that are at least readable as strings.
3. The `EnvironmentName` key is set to the same value as `EnvironmentNames` (comma-delimited list of environment names) - should it just be the first environment? Or only present if there is a single environment?
4. There are two …
=> Move token dictionary creation to ConfigurationPropertyHolder

README.markdown, appveyor.yml, build.ps1, product/roundhouse.console/DotnetToolSettings.xml, product/roundhouse.console/Program.cs, product/roundhouse.console/roundhouse.console.csproj, product/roundhouse.console/roundhouse.tool.nuspec, product/roundhouse.databases.access/roundhouse.databases.access.csproj, product/roundhouse.databases.mysql/roundhouse.databases.mysql.csproj, product/roundhouse.databases.oracle/roundhouse.databases.oracle.csproj, product/roundhouse.databases.postgresql/roundhouse.databases.postgresql.csproj, product/roundhouse.databases.sqlite/roundhouse.databases.sqlite.csproj, product/roundhouse.databases.sqlserver/roundhouse.databases.sqlserver.csproj, product/roundhouse.databases.sqlserver2000/roundhouse.databases.sqlserver2000.csproj, product/roundhouse.databases.sqlserverce/roundhouse.databases.sqlserverce.csproj, product/roundhouse.lib.merged/roundhouse.lib.merged.csproj, product/roundhouse.tasks/roundhouse.tasks.csproj, product/roundhouse.tests.integration/roundhouse.tests.integration.csproj, product/roundhouse.tests/roundhouse.tests.csproj, product/roundhouse/roundhouse.csproj
This adds publishing of RoundhousE as a .net core global tool, which drastically simplifies installation of the .net core version of RoundhousE on all platforms.
To test the installation, before the tool is actually pushed to nuget, you need to add the nuget folder on install, like this (from the project root folder):
1. `./build.ps1`
1. `dotnet tool install --add-source ./code_drop/packages --version 1.0.0-RC.2 -g dotnet-roundhouse`
(change version number as needed)
You can then see the tool is installed:
`dotnet tool list -g`
output from my box:
```
Package Id             Version         Commands       
------------------------------------------------------
dotnet-outdated        2.0.0           dotnet-outdated
dotnet-roundhouse      1.0.0-rc.2      dotnet-rh      
```
And you can …
=> Issue 332 - Publish as a dotnet core global tool

product/roundhouse.databases.access/orm/ScriptsRunMapping.cs, product/roundhouse.databases.mysql/orm/ScriptsRunMapping.cs, product/roundhouse.databases.postgresql/orm/ScriptsRunMapping.cs, product/roundhouse.databases.sqlite/orm/ScriptsRunMapping.cs, product/roundhouse.databases.sqlserver/orm/ScriptsRunMapping.cs, product/roundhouse.databases.sqlserver2000/orm/ScriptsRunMapping.cs, product/roundhouse.databases.sqlserverce/orm/SciptsRunMapping.cs, product/roundhouse/databases/DefaultDatabase.cs
Part 2 of #331
Also including Part 1 (#337)
Lazy load of scripts_run column
| Run1 | Run 2 | Run 3 | Average |
|---|---|---|---|
| 2:17.248 | 1:52.886 | 1:59.482 | 2:03.205 |
| Run1 | Run 2 | Run 3 | Average |
|---|---|---|---|
| 1.34.084 | 1:29.291 | 1:38.848 | 1:34.074 |
| Run1 | Run 2 | Run 3 | Average |
|---|---|---|---|
| 1:31.176 | 1:31.206 | 1:29.419 | 1:30.600 |
=> Lazy load Script text

product/roundhouse.tests/infrastructure/filesystem/KnownFolders.cs, product/roundhouse/infrastructure.app/builders/KnownFoldersBuilder.cs, product/roundhouse/infrastructure/filesystem/DotNetFileSystemAccess.cs, product/roundhouse/infrastructure/filesystem/FileSystemAccess.cs
Make sure there are no invalid paths in the folder used to log migrations. Currently filters out `Path.GetInvalidChars()` and `:`. Maybe not necessary to explicitly exclude a colon, as it is valid on other platforms than Windows, but, anyways... makes the directories more unified across platforms.
=> Issue #355: Replace invalid chars in path

product/roundhouse.databases.oracle/OracleDatabase.cs, product/roundhouse.databases.oracle/PLSQLSpecific.cs
We were having an issue using roundhouse over numerous schemas on the same oracle instance. 
If we had 2 schemas DB_DEV and DB_TEST, roundhouse would run fine on the DB_DEV instance, create the 3 roundhouse tables and populate them fine. When we came to run then on DB_TEST it would fail stating that the roundhouse tables did not exist. It appeared that it was checking for the existance of the roundhouse tables without taking into account it was under a different schema. 
After a bit of looking about we noticed the PLSQLSpecific class in the roundhouse.databases.oracle section, after re-instating that roundhouse works like a charm.
If this isnt a great idea and there is another way to address the issue we were noticing i'd be very interested to hear some thoughts.
=> Added methods in the Oracle DB section to use the PLSQL methods

Dockerfile, README.markdown
Added Dockerfile, which installs `dotnet-roundhouse` on a Microsoft 2.2. sdk .net core sdk image.
Fixes #342
=> Add docker distribution of RoundhousE

product/roundhouse.databases.mysql/parser/Scanner.cs, product/roundhouse.databases.mysql/parser/Token.cs, product/roundhouse.tests/sqlsplitters/MySqlStatementSplitterSpecs.cs
I ran into an issue this week and it turns out (much to my embarrassment) that the MySQL parser doesn't handle single (') quoted values, only back-tick or double quoted. This change adds single quoted values to the parser. It also adds a new test case for single quoted values.
I have another project where I test these changes against a database, you can find a [more practical example there](https://github.com/cmiles74/rh-mysql-sproc-test/blob/master/up/0003_Parsed_Statement.sql).
Thank you! `:-D`
=> Updated parser to handle single quoted values

appveyor.yml
Due to error running latest GitVersion on AppVeyor.
Got the following error with latest (5.0.1): Unrecognized configuration section dllmap
=> Locked GitVersion to 4.0.0 in appveyor.yml 

product/roundhouse.core/infrastructure.app/ApplicationConfiguraton.cs, product/roundhouse.core/migrators/DefaultDatabaseMigrator.cs, product/roundhouse.core/migrators/DefaultHashGenerator.cs, product/roundhouse.core/migrators/HashGenerator.cs, product/roundhouse.tests/migrators/DefaultHashGeneratorSpecs.cs
Hash comparison should ignore end-of-line variations, but it fails in one scenario:
- when the original hash was calculated by an older RH version, which didn't normalize the script to LF line endings before hashing
- and the original script had CRLF line endings
- and the same file, but with LF line endings, is executed by the migrator.
This PR refactors hash generation and comparison into a separate class, adds unit tests that demonstrate the bug and fixes it.
=> Fix EOL-related hash comparison bug

product/roundhouse.core/roundhouse.core.csproj
It would appear that this is now used as part of https://github.com/chucknorris/roundhouse/pull/388/files#diff-3139d803d9b04a25c7e3beaa80e76f4cR16
When consuming this in a framework project, this dependency is required
=> Adding System.ValueTuple dependency

product/roundhouse.core/infrastructure/filesystem/DotNetFileSystemAccess.cs
As seen in #386 directories are not ordered when they're retrieved. This results in different behaviour when executing up scripts on windows vs linux (assuming it's actually different due to the way the different filesystems work under the hood).
This adds an option to force the directories to be retrieved in order so that scripts run in a repeatable manner. The config defaults to false to avoid breaking any existing executions based on the old behaviour.
Running `Directory.GetDirectories(upPath)` on windows vs linux
=> Order directories by path

product/roundhouse.console/Program.cs, product/roundhouse.core/consoles/DefaultConfiguration.cs, product/roundhouse.core/infrastructure.app/ConfigurationPropertyHolder.cs, product/roundhouse.databases.sqlserver/ReliableSqlConnection.cs, product/roundhouse.databases.sqlserver/SqlServerDatabase.cs, product/roundhouse.tasks/Roundhouse.cs
Added support for access tokens for use in Azure SQL.
Unfortunately, I'm unable to test this against Azure. I did test against a local SQL Server instance and the property is set on the underlying connection.
Possibly fixes #344 and #343
=> Add Access Token support to SqlServerDatabase

product/roundhouse.console/roundhouse.tool.nuspec, product/roundhouse.core/roundhouse.core.csproj, product/roundhouse.databases.access/roundhouse.databases.access.csproj, product/roundhouse.databases.mysql/roundhouse.databases.mysql.csproj, product/roundhouse.databases.oracle/roundhouse.databases.oracle.csproj, product/roundhouse.databases.postgresql/roundhouse.databases.postgresql.csproj, product/roundhouse.databases.sqlite/roundhouse.databases.sqlite.csproj, product/roundhouse.databases.sqlserver/roundhouse.databases.sqlserver.csproj, product/roundhouse.databases.sqlserver2000/roundhouse.databases.sqlserver2000.csproj, product/roundhouse.databases.sqlserverce/roundhouse.databases.sqlserverce.csproj, product/roundhouse.lib/roundhouse.lib.csproj, product/roundhouse.tasks/roundhouse.tasks.csproj, roundhouse.sln
iconUrl is deprecated. Replace with in -package icon
=> iconUrl -> icon in nuspec file

Dockerfile
Change the ENTRYPOINT to array syntax in order to allow passing parameters to rh from docker run.
This should fix issue #414
=> Fix Dockerfile to honor arguments

Dockerfile, build.ps1, product/roundhouse.console/roundhouse.console.csproj, product/roundhouse.console/roundhouse.tool.nuspec, product/roundhouse.test.merged/roundhouse.test.merged.csproj, product/roundhouse.tests/roundhouse.tests.csproj, roundhouse.sln
There are problems running RoundhousE on systems with only netcoreapp3.1 installed, as it is compiled against netcoreapp2.1. As 2.1 is in end-of-life, just upgrade to 3.1 all over
=> Upgrade all netcoreapp2.1  to netcoreapp3.1

product/roundhouse.console/roundhouse.console.csproj, product/roundhouse.tests/roundhouse.tests.csproj
There were warnings on different versions (n-level dependencies) of System.Data and one other. Fixed by adding direct ref from client projects
=> Fixed warnings with different versions of System.* nuget packages
