product/roundhouse.console/Program.cs
product/roundhouse.tasks/Roundhouse.cs
product/roundhouse/consoles/DefaultConfiguration.cs
product/roundhouse/infrastructure.app/ApplicationConfiguraton.cs
product/roundhouse/infrastructure.app/ConfigurationPropertyHolder.cs
product/roundhouse/init/Initializer.cs
product/roundhouse/roundhouse.csproj

The goal of this pull request is to enable a quicker start with roundhouse, by providing a `rh --init` command that will set up all of the folders for you.

Adding an initialization command to roundhouse

---

product/roundhouse/databases/AdoNetDatabase.cs

this will prevent any other errors from being hidden. fixes #173.

only retry on sql connection errors

---

product/roundhouse.console/Program.cs

fixes Searchallinsteadoftraverse bug

---

product/roundhouse/migrators/DefaultDatabaseMigrator.cs

I believe i fixed the line ending
Supersedes https://github.com/chucknorris/roundhouse/pull/97

implementing baseline and dryrun if statements

---

product/roundhouse.databases.sqlserver2000/SqlServerDatabase.cs

Squashed commits from @sicil1ano's master branch per @ferventcoder's request.
Fixes #176, closes #179.

(GH-176) Fix Sql 2000 database creation

---

product/roundhouse.databases.sqlserver/SqlServerDatabase.cs

Rh fails to remove database, when running against existing azure database using `-drop` switch.
1. `msdb.dbo.sp_delete_database_backuphistory` is not supported in Azure Database
The error message is following:
```
EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = 'Roundhouse'
Msg 40515, Level 15, State 1, Line 25
Reference to database and/or server name in 'msdb.dbo.sp_delete_database_backuphistory' is not supported in this version of SQL Server.
```
2. `ALTER DATABASE DbName SET SINGLE_USER WITH ROLLBACK IMMEDIATE` is not
needed in Azure Database, because `DROP DATABASE DbName` works well
without it regardless of users being connected. While this statement
when executed on Azure Database results with following error:
```
Msg 42008, Level 16, State 5, Line 1
ODBC error: …
```

Add drop database support for Azure Database

---

product/roundhouse.console/Program.cs
product/roundhouse.tasks/Roundhouse.cs
product/roundhouse/consoles/DefaultConfiguration.cs
product/roundhouse/infrastructure.app/ConfigurationPropertyHolder.cs
product/roundhouse/migrators/DefaultDatabaseMigrator.cs

fixes #226 skips over one and updates baseline for onetime scripts which
have changed.

added switch warnandignoreononetimescriptchanges

---

.editorconfig
CONTRIBUTING.markdown
roundhouse.sln.DotSettings

Added a contributions guide with details about the coding standards and some basic tooling support for ReSharper and editorconfig.
The pull request replaces the messed up PR 254 which has been closed in hair pulling frustration.

(GH-190) Coding Standards

---

product/roundhouse.databases.oracle/RoundhousEOracleDriver.cs
product/roundhouse.databases.oracle/orm/ScriptsRunErrorMapping.cs
product/roundhouse.databases.oracle/orm/ScriptsRunMapping.cs
product/roundhouse.databases.oracle/roundhouse.databases.oracle.csproj
product/roundhouse/infrastructure/persistence/NHibernateSessionFactoryBuilder.cs

We added a fix for issue #37 because the scripts failed in our Oracle environment
This is the same fix as in pull request #73, but isolated from the AnyCpu fix

Fix for Oracle and NHibernate Blobs

---

product/roundhouse.console/app.config
product/roundhouse.console/packages.config
product/roundhouse.console/roundhouse.console.csproj
product/roundhouse.tasks/packages.config
product/roundhouse.tasks/roundhouse.tasks.csproj
product/roundhouse.tests.integration/packages.config
product/roundhouse.tests.integration/roundhouse.tests.integration.csproj
product/roundhouse.tests/packages.config
product/roundhouse.tests/roundhouse.tests.csproj
product/roundhouse/infrastructure.app/logging/log4net.config.xml
product/roundhouse/packages.config
product/roundhouse/roundhouse.csproj

Closes #215
taken from:
https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure/logging/log4net.mono.config.xml#L6
@ChrisMissal

Switching to Managed Colored Console for mono support

---

product/roundhouse.databases.postgresql/PostgreSQLDatabase.cs
product/roundhouse.databases.postgresql/TableCreationScripts.cs
product/roundhouse.databases.postgresql/orm/ScriptsRunErrorMapping.cs
product/roundhouse.databases.postgresql/orm/ScriptsRunMapping.cs
product/roundhouse.databases.postgresql/orm/VersionMapping.cs

Updated postgreSQL related scripts to handle schema correctly. Tested in my postgres environment and worked as a charm! :)

TableCreationScripts for PostgreSQL do not handle schema name properly.

---

product/roundhouse.databases.sqlserverce/Properties/AssemblyInfo.cs
product/roundhouse.databases.sqlserverce/SqlServerCEDatabase.cs
product/roundhouse.databases.sqlserverce/orm/SciptsRunMapping.cs
product/roundhouse.databases.sqlserverce/orm/ScriptsRunErrorMapping.cs
product/roundhouse.databases.sqlserverce/orm/VersionMapping.cs
product/roundhouse.databases.sqlserverce/packages.config
product/roundhouse.databases.sqlserverce/roundhouse.databases.sqlserverce.csproj
product/roundhouse/databases/DefaultDatabase.cs
product/roundhouse/infrastructure.app/DatabaseTypeSynonyms.cs
product/roundhouse/infrastructure/persistence/NHibernateSessionFactoryBuilder.cs
roundhouse.sln

supercedes #139 
- updated to use SqlCeConnectionStringBuilder
- just using System.IO.File - this provider is Windows only

SQL Server Compact Edition support

---

product/roundhouse.console/Program.cs
product/roundhouse.tasks/Roundhouse.cs
product/roundhouse.tests/TestExtensions.cs
product/roundhouse.tests/infrastructure.app/tokens/TokenReplacerSpecs.cs
product/roundhouse.tests/infrastructure.app/tokens/UserTokenParserSpecs.cs
product/roundhouse.tests/roundhouse.tests.csproj
product/roundhouse/consoles/DefaultConfiguration.cs
product/roundhouse/infrastructure.app/ConfigurationPropertyHolder.cs
product/roundhouse/infrastructure.app/UserTokenParser.cs
product/roundhouse/infrastructure.app/tokens/TokenReplacer.cs
product/roundhouse/roundhouse.csproj

This recreates and supersedes #231 so we can have a rapid review and merge.
This will also supersede #267 
Absent feedback/corrections, I will merge this on 10/14/2017

Add User Tokens to Roundhouse

---

product/roundhouse.console/Program.cs
product/roundhouse.console/roundhouse.console.csproj
product/roundhouse/infrastructure.app/ApplicationConfiguraton.cs
product/roundhouse/infrastructure.app/ConfigurationPropertyHolder.cs

(Completes #293 in a better way).

Removed obsolete properties, RecoveryModeSimple and EnvironmentName

---

product/roundhouse.tests.integration/databases/SqLiteDatabaseSpecs.cs
product/roundhouse.tests.integration/databases/SqlServerCEDatabaseSpecs.cs
product/roundhouse.tests.integration/roundhouse.tests.integration.csproj

SSIA. Integration tests are good things. Makes change so much easier.

Added integration tests for SqLite and SqlServerCE

---

README.markdown

Are we ready for a release?
I've drafted some release notes, but it's my first time here, so I would love if you could look over it, @BiggerNoise or @ferventcoder: https://github.com/chucknorris/roundhouse/releases/edit/untagged-36255f1bd77ecb71bcdb
Also, could you please look through the issues that are open here, and see if you agree that we can consider them part of the release, and close them?
https://github.com/chucknorris/roundhouse/milestone/8
I would also need some credentials to Chocolatey and NuGet if you want me to do the actual push there, @ferventcoder 
Thanks.

Updated README.markdown for 0.9.0 release

---

product/roundhouse.databases.mysql/MySqlDatabase.cs

Fixed MySql DatabaseName not getting set

---

product/roundhouse.databases.mysql/MySqlDatabase.cs

Fixed issue #315 MySql runAfterCreateDatabase not getting executed

Updated MySql create_database_script to return Created flag

---

README.markdown

This links to my Paypal account. I doubt we have a super high volume of donations, so I was thinking that I'll distribute on an ad-hoc basis. @erikbra - please send me an email (same username at gmail) and I'll be able to settle up.

Update donation link to current paypal account

---

README.markdown

@erikbra I must have been taking stupid pills this morning, but I can't seem to figure out how to get the MyGet artifacts available to someone that isn't logged into to MyGet.
I know it's possible, because I can see the feeds for the ChuckNorris project. If you can fix the link, then hopefully we can start engaging some testers.
Thanks

WIP - Add a pointer to the 1.0.0 branch

---

product/roundhouse/databases/DefaultDatabase.cs

Part 1 of #331 
Just script caching improvements
| Run1 | Run 2 | Run 3 | Average |
|---|---|---|---|
| 2:17.248 | 1:52.886 | 1:59.482 | 2:03.205 |
| Run1 | Run 2 | Run 3 | Average |
|---|---|---|---|
| 1.34.084 | 1:29.291 | 1:38.848 | 1:34.074 |

Update DefaultDatabase to use and trust the script cache

---

build.ps1
product/roundhouse.console/DotnetToolSettings.xml
product/roundhouse.console/roundhouse.console.csproj
product/roundhouse.databases.access/roundhouse.databases.access.csproj
product/roundhouse.databases.mysql/roundhouse.databases.mysql.csproj
product/roundhouse.databases.oracle/roundhouse.databases.oracle.csproj
product/roundhouse.databases.postgresql/roundhouse.databases.postgresql.csproj
product/roundhouse.databases.sqlite/roundhouse.databases.sqlite.csproj
product/roundhouse.databases.sqlserver/roundhouse.databases.sqlserver.csproj
product/roundhouse.databases.sqlserver2000/roundhouse.databases.sqlserver2000.csproj
product/roundhouse.databases.sqlserverce/roundhouse.databases.sqlserverce.csproj
product/roundhouse.tasks/roundhouse.tasks.csproj
product/roundhouse.tests.integration/roundhouse.tests.integration.csproj
product/roundhouse.tests/roundhouse.tests.csproj
product/roundhouse/roundhouse.csproj

Upgraded a couple of Nuget packages too, to newest minor version

Changed dotnet tool command name to 'rh'.

---

appveyor.yml
product/roundhouse.databases.sqlite/roundhouse.databases.sqlite.csproj
product/roundhouse.lib.merged/roundhouse.lib.nuspec

Managed to merge a PR #346 which did not build (packaging went wrong) - and for some ugly reason, the build didn't fail on AppVeyor - need to follow this separately.

Fixed version diff btw deps and nuspec deps

---

build.ps1
product/roundhouse.console/roundhouse.console.csproj

so that standard roundhouse nuget package is generated correctly too

Fixed build script build.ps1

---

build.ps1
product/roundhouse.console/roundhouse.console.csproj
product/roundhouse.console/roundhouse.tool.nuspec

Run dotnet publish before pack, to get all dependencies in the package.

Issue 352 - Can't find Antlr

---

product/roundhouse.databases.sqlite/roundhouse.databases.sqlite.csproj

- Changed hard-coded `net461` with `$(TargetFramework)`
- Changed casing of nuget package folders to lowercase (as they are on case-aware file systems)

Solved #348: Build fail on Docker Linux container

---

product/roundhouse.lib.merged/roundhouse.lib.nuspec

This is taken from the project filess used in roundhouse.lib.merged
Fixes #365

Update nuspec to match the dependencies needed

---

product/roundhouse.console/Program.cs
product/roundhouse.core/consoles/DefaultConfiguration.cs
product/roundhouse.core/infrastructure.app/ConfigurationPropertyHolder.cs
product/roundhouse.core/migrators/DefaultDatabaseMigrator.cs
product/roundhouse.tasks/Roundhouse.cs

Provides a solution for #354 by adding a new configuration property

Add switch to not store full text of scripts run

---

product/roundhouse.core/databases/Database.cs
product/roundhouse.core/databases/DefaultDatabase.cs
product/roundhouse.core/databases/MockDatabase.cs
product/roundhouse.core/databases/SqlServerLiteSpeedDatabase.cs
product/roundhouse.core/migrators/DefaultDatabaseMigrator.cs
product/roundhouse.databases.oracle/OracleDatabase.cs
product/roundhouse.databases.sqlserverce/SqlServerCEDatabase.cs

Provides a fix for #275 
If unit tests are to be written, please guide me in the right direction for the correct class.

Prevent dryrun from writing version records

---

Dockerfile

Hi team, a small PR to update the version of .NET Core SDK used in the Dockerfile.

Update Dockerfile to use .NET Core SDK 3.1

---

build.ps1
product/roundhouse.console/roundhouse.console.csproj
product/roundhouse.core/databases/DefaultDatabase.cs
product/roundhouse.core/infrastructure/extensions/TypeExtensions.cs
product/roundhouse.core/sqlsplitters/DefaultDatabase.cs
product/roundhouse.databases.access/AccessDatabase.cs
product/roundhouse.databases.access/roundhouse.databases.access.csproj
product/roundhouse.databases.oracle/OracleDatabase.cs
product/roundhouse.databases.oracle/roundhouse.databases.oracle.csproj
product/roundhouse.lib/roundhouse.lib.csproj
product/roundhouse.tasks/roundhouse.tasks.csproj
product/roundhouse.tests/databases/DbProviderFactories.cs
product/roundhouse.tests/infrastructure/filesystem/DotNetFileSystemAccessSpecs.cs
product/roundhouse.tests/roundhouse.tests.csproj
product/roundhouse.tests/sqlsplitters/StatementSplitterSpecs.cs

* Added _WINDOWS ifdef variable
* Run tests for both net461 and netcore2.1
* Added PackageReference to Microsoft.NETFramework.ReferenceAssemblies
to be able to build on non-Windows platforms
* A bit more of #ifdefs on NET461 and _WINDOWS to avoid failing tests on non-Windows
* Some small adjustments to build.ps1

Changes in build and tests to improve non-Windows builds

---

.gitattributes

- So that it works when building with docker

Changed line ending of Extract-Resources.ps1 to LF
